#this one file will execute the whole app
import ui, texts as tx
from tkinter import Checkbutton, IntVar

#
#switching modes
#
isdark = IntVar()
mode = Checkbutton(ui.okno, text=tx.darkmode, variable=isdark, onvalue=1, offvalue=0)
def dark():
 if isdark.get() == 0:
  ui.okno.config(bg='white')
  mode.config(bg='white',fg='black')
  ui.choose.config(bg='white',fg='black')
  ui.stvorec.config(bg='white',fg='black')
  ui.obdlznik.config(bg='white',fg='black')
  ui.kruh.config(bg='white',fg='black')
  ui.pyveta.config(bg='white',fg='black')
  ui.l1.config(bg='white',fg='black')
  ui.l2.config(bg='white',fg='black')
  ui.l3.config(bg='white',fg='black')
  ui.l4.config(bg='white',fg='black')
  ui.l_obsahstvorca.config(bg='white',fg='black')
  ui.l_obsahobdlznika.config(bg='white',fg='black')
  ui.l_obsahkruhu.config(bg='white',fg='black')
  ui.l_vysledokvety.config(bg='white',fg='black')
  ui.l_obvodstvorca.config(bg='white',fg='black')
  ui.l_obvodobdlznika.config(bg='white',fg='black')
  ui.l_obvodkruhu.config(bg='white',fg='black')
  ui.l_dlzkaodvesny.config(bg='white',fg='black')
  ui.obsah.config(bg='white',fg='black')
  ui.obvod.config(bg='white',fg='black')
  ui.vysledok.config(bg='white',fg='black')
  ui.realna_dlzka.config(bg='white',fg='black')
  ui.dlzka.config(bg='white',fg='black')
  ui.a.config(bg='white',fg='black')
  ui.b.config(bg='white',fg='black')
  ui.r.config(bg='white',fg='black')
  ui.obsah.config(bg='white',fg='black')
  ui.obvod.config(bg='white',fg='black')
  ui.vysledok.config(bg='white',fg='black')
  ui.realna_dlzka.config(bg='white',fg='black')

 if isdark.get() == 1:
  ui.okno.config(bg='black')
  mode.config(bg='black',fg='white')
  ui.choose.config(bg='black',fg='white')
  ui.stvorec.config(bg='black',fg='white')
  ui.obdlznik.config(bg='black',fg='white')
  ui.kruh.config(bg='black',fg='white')
  ui.pyveta.config(bg='black',fg='white')
  ui.l1.config(bg='black',fg='white')
  ui.l2.config(bg='black',fg='white')
  ui.l3.config(bg='black',fg='white')
  ui.l4.config(bg='black',fg='white')
  ui.l_obsahstvorca.config(bg='black',fg='white')
  ui.l_obsahobdlznika.config(bg='black',fg='white')
  ui.l_obsahkruhu.config(bg='black',fg='white')
  ui.l_vysledokvety.config(bg='black',fg='white')
  ui.l_obvodstvorca.config(bg='black',fg='white')
  ui.l_obvodobdlznika.config(bg='black',fg='white')
  ui.l_obvodkruhu.config(bg='black',fg='white')
  ui.l_dlzkaodvesny.config(bg='black',fg='white')
  ui.dlzka.config(bg='black',fg='white')
  ui.a.config(bg='black',fg='white')
  ui.b.config(bg='black',fg='white')
  ui.r.config(bg='black',fg='white')
  ui.obsah.config(bg='black',fg='white')
  ui.obvod.config(bg='black',fg='white')
  ui.vysledok.config(bg='black',fg='white')
  ui.realna_dlzka.config(bg='black',fg='white')
mode.config(command=dark)

