from tkinter import Checkbutton, IntVar
import ui

app = ui.UI
isdark = IntVar()
mode = Checkbutton(app.okno, text="Tmavý režim", variable=isdark, onvalue=1, offvalue=0)

def dark():
 if isdark.get() == 0:
  app.okno.config(bg='white')
  mode.config(bg='white',fg='black')
  app.choose.config(bg='white',fg='black')
  app.stvorec.config(bg='white',fg='black')
  app.obdlznik.config(bg='white',fg='black')
  app.kruh.config(bg='white',fg='black')
  app.pyveta.config(bg='white',fg='black')
  app.l1.config(bg='white',fg='black')
  app.l2.config(bg='white',fg='black')
  app.l3.config(bg='white',fg='black')
  app.l4.config(bg='white',fg='black')
  app.l_obsahstvorca.config(bg='white',fg='black')
  app.l_obsahobdlznika.config(bg='white',fg='black')
  app.l_obsahkruhu.config(bg='white',fg='black')
  app.l_vysledokvety.config(bg='white',fg='black')
  app.l_obvodstvorca.config(bg='white',fg='black')
  app.l_obvodobdlznika.config(bg='white',fg='black')
  app.l_obvodkruhu.config(bg='white',fg='black')
  app.l_dlzkaodvesny.config(bg='white',fg='black')
  app.obsah.config(bg='white',fg='black')
  app.obvod.config(bg='white',fg='black')
  app.vysledok.config(bg='white',fg='black')
  app.realna_dlzka.config(bg='white',fg='black')
  app.dlzka.config(bg='white',fg='black')
  app.a.config(bg='white',fg='black')
  app.b.config(bg='white',fg='black')
  app.r.config(bg='white',fg='black')
  app.obsah.config(bg='white',fg='black')
  app.obvod.config(bg='white',fg='black')
  app.vysledok.config(bg='white',fg='black')
  app.realna_dlzka.config(bg='white',fg='black')

 if isdark.get() == 1:
  app.okno.config(bg='black')
  mode.config(bg='black',fg='white')
  app.choose.config(bg='black',fg='white')
  app.stvorec.config(bg='black',fg='white')
  app.obdlznik.config(bg='black',fg='white')
  app.kruh.config(bg='black',fg='white')
  app.pyveta.config(bg='black',fg='white')
  app.l1.config(bg='black',fg='white')
  app.l2.config(bg='black',fg='white')
  app.l3.config(bg='black',fg='white')
  app.l4.config(bg='black',fg='white')
  app.l_obsahstvorca.config(bg='black',fg='white')
  app.l_obsahobdlznika.config(bg='black',fg='white')
  app.l_obsahkruhu.config(bg='black',fg='white')
  app.l_vysledokvety.config(bg='black',fg='white')
  app.l_obvodstvorca.config(bg='black',fg='white')
  app.l_obvodobdlznika.config(bg='black',fg='white')
  app.l_obvodkruhu.config(bg='black',fg='white')
  app.l_dlzkaodvesny.config(bg='black',fg='white')
  app.dlzka.config(bg='black',fg='white')
  app.a.config(bg='black',fg='white')
  app.b.config(bg='black',fg='white')
  app.r.config(bg='black',fg='white')
  app.obsah.config(bg='black',fg='white')
  app.obvod.config(bg='black',fg='white')
  app.vysledok.config(bg='black',fg='white')
  app.realna_dlzka.config(bg='black',fg='white')
