#this file is for switching between light and dark mode
import ui

def dark():
 if ui.isdark.get() == 0:
  ui.okno.config(bg='white')
  ui.mode.config(bg='white',fg='black')
  ui.choose.config(bg='white',fg='black')
  ui.stvorec.config(bg='white',fg='black')
  ui.obdlznik.config(bg='white',fg='black')
  ui.kruh.config(bg='white',fg='black')
  ui.pyveta.config(bg='white',fg='black')
  ui.l1.config(bg='white',fg='black')
  ui.l2.config(bg='white',fg='black')
  ui.l3.config(bg='white',fg='black')
  ui.l4.config(bg='white',fg='black')
  ui.l_obsahstvorca.config(bg='white',fg='black')
  ui.l_obsahobdlznika.config(bg='white',fg='black')
  ui.l_obsahkruhu.config(bg='white',fg='black')
  ui.l_vysledokvety.config(bg='white',fg='black')
  ui.l_obvodstvorca.config(bg='white',fg='black')
  ui.l_obvodobdlznika.config(bg='white',fg='black')
  ui.l_obvodkruhu.config(bg='white',fg='black')
  ui.l_dlzkaodvesny.config(bg='white',fg='black')
  ui.obsah.config(bg='white',fg='black')
  ui.obvod.config(bg='white',fg='black')
  ui.vysledok.config(bg='white',fg='black')
  ui.realna_dlzka.config(bg='white',fg='black')
  ui.dlzka.config(bg='white',fg='black')
  ui.a.config(bg='white',fg='black')
  ui.b.config(bg='white',fg='black')
  ui.r.config(bg='white',fg='black')
  ui.obsah.config(bg='white',fg='black')
  ui.obvod.config(bg='white',fg='black')
  ui.vysledok.config(bg='white',fg='black')
  ui.realna_dlzka.config(bg='white',fg='black')

 if ui.isdark.get() == 1:
  ui.okno.config(bg='black')
  ui.mode.config(bg='black',fg='white')
  ui.choose.config(bg='black',fg='white')
  ui.stvorec.config(bg='black',fg='white')
  ui.obdlznik.config(bg='black',fg='white')
  ui.kruh.config(bg='black',fg='white')
  ui.pyveta.config(bg='black',fg='white')
  ui.l1.config(bg='black',fg='white')
  ui.l2.config(bg='black',fg='white')
  ui.l3.config(bg='black',fg='white')
  ui.l4.config(bg='black',fg='white')
  ui.l_obsahstvorca.config(bg='black',fg='white')
  ui.l_obsahobdlznika.config(bg='black',fg='white')
  ui.l_obsahkruhu.config(bg='black',fg='white')
  ui.l_vysledokvety.config(bg='black',fg='white')
  ui.l_obvodstvorca.config(bg='black',fg='white')
  ui.l_obvodobdlznika.config(bg='black',fg='white')
  ui.l_obvodkruhu.config(bg='black',fg='white')
  ui.l_dlzkaodvesny.config(bg='black',fg='white')
  ui.dlzka.config(bg='black',fg='white')
  ui.a.config(bg='black',fg='white')
  ui.b.config(bg='black',fg='white')
  ui.r.config(bg='black',fg='white')
  ui.obsah.config(bg='black',fg='white')
  ui.obvod.config(bg='black',fg='white')
  ui.vysledok.config(bg='black',fg='white')
  ui.realna_dlzka.config(bg='black',fg='white')


ui.mode.config(command=dark)