from tkinter import *

class UI:
 okno = Tk()
 okno.geometry('500x500')
 okno.eval('tk::PlaceWindow . center')
 okno.title="Matika"
 choose = Label(text="Vyber tvar:")
 strana1 = StringVar()
 strana2 = StringVar()
 dlzka = Entry(okno, textvariable=strana1)
 a = Entry(okno, textvariable=strana1)
 b = Entry(okno, textvariable=strana2)
 r = Entry(okno, textvariable=strana1)
 l_obsahstvorca = Label(okno)
 l_obsahobdlznika = Label(okno)
 l_obsahkruhu = Label(okno)
 l_vysledokvety = Label(okno)
 l_obvodstvorca = Label(okno)
 l_obvodobdlznika = Label(okno)
 l_obvodkruhu = Label(okno)
 l_dlzkaodvesny = Label(okno)
 obsah = Button(text="Obsah", padx=50, pady=10)
 obvod = Button(text="Obvod", padx=50, pady=10)
 vysledok = Button(text="Výsledok", padx=50, pady=10)
 realna_dlzka = Button(text="Reálna dĺžka", padx=50, pady=10)
 l1 = Label(text="Dĺžka strany:")
 l2 = Label(text="a:")
 l3 = Label(text="b:")
 l4 = Label(text="Polomer:")
 i = IntVar()
 isdark = IntVar()
 stvorec = Radiobutton(okno, text="Štvorec", variable=i, value=1)
 obdlznik = Radiobutton(okno, text="Obdĺžnik", variable=i, value=2)
 kruh = Radiobutton(okno, text="Kruh", variable=i, value=3)
 pyveta = Radiobutton(okno, text="Pytagorova veta", variable=i, value=4)
 lang = Menu(okno)